version: "3.9"
services:
  backend:
    build: ./backend
    expose:
      - "3000"
    ports:
      - "3001:3000"  # Maps host port 3001 to container port 3000
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend