version: "3.9"
services:
  # TODO: Define backend service
  # TODO: Define frontend service
  # TODO: Add ports and dependencies
version: "3.9"
services:
  backend:
    build: ./backend
    expose:
      - "5000"
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend